name: Expo CI
on: [ push, pull_request ]
jobs:
  publish:
    name: Install and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: expo/expo-github-action@v5
        with:
          expo-packager: npm
          expo-cache: true
      - run: npm ci
      - run: expo doctor
